### ISSUE TITLE
Presets tab is empty (find presets paths)

### ISSUE THREAD

**Issue by magnetophon** [iurie-sw/geonkick#86] opened 2020-06-11 09:50 UTC
It looks like this for me:
![screenshot_20200611_114417](https://user-images.githubusercontent.com/7645711/84370992-4f01ea80-abd9-11ea-9e64-2c2dc5ace476.png)

The presets seem to be correctly installed in ``$PREFIX/share/geonkick/presets``

Example file:
``/nix/store/xvrbkz4fwj8fvjfpsikyhh8ikf741848-geonkick-2.2.0/share/geonkick/presets/AVL-Drumkit/README``

**Comment by iurienistor** [comment] 2020-06-11 10:06
Geonkick for now looks only under these paths for presets.

/usr/share/geonkick/presets/
/usr/local/share/geonkick/presets/
/home/<user>/.local/geonkick/presets/

**Comment by magnetophon** [comment] 2020-06-11 10:20
Cool, when I symlink them to /home/user/.local/geonkick/presets/ it works.
Thank you, also for #87, as that would allow proper installation in non standard paths.
My distro cannot install in standard paths, that's is what allows it to have [many nice features](https://nixos.org/features.html).

**Comment by iurienistor** [comment] 2020-06-11 10:21
@magnetophon probably I also need to take in consideration also $PATH and look there for paths that contain */share/geonkick/presets

**Comment by iurienistor** [comment] 2020-06-11 18:57
duplicate of

**Closed by iurienistor** 2020-06-11 18:57 UTC
Labels: duplicate, feature
