### ISSUE TITLE
Renaming elements in Kit: Selection and cursor position does not work as expected

### ISSUE THREAD

**Issue by Ploppz** [iurie-sw/geonkick#122] opened 2020-09-06 14:20 UTC
If you double click a name, then Ctrl+A to select all the text, if you press a key then to replace the text, the character only gets prepended to the existing text.

Furthermore, it doesn't seem possible to change the text cursor location with mouse, only with keyboard.

So the only way right now to change the name completely is: Double click, hold right arrow, hold backspace, write the new name.

**Comment by iurienistor** [comment] 2020-09-07 04:54
Hi,
Geonkick uses its own developed gui toolkit called Redkite, and many widgets still lack features, including line editing which a lot of work to do in order to comply to the standard. I'll mark this issue a duplicate of https://github.com/iurie-sw/redkite/issues/20

**Closed** 2020-09-07 04:55 UTC
Labels: duplicate
